<?php
/**
 * Digit Software Solutions.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category  Dss
 * @package   Dss_FacebookPixel
 * @author    Extension Team
 * @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
 */
/**
 * @var $block \Dss\FacebookPixel\Block\Code
 */
$pageView = $block->checkDisable();
$data   = $block->getFacebookPixelData();
$id     = $data['id'];
$action = $data['full_action_name'];
$product = $block->getProduct();
$category = $block->getCategory();
$registrationData = $block->getRegistration();
$addToWishlist = $block->getAddToWishList();
$initiateCheckout = $block->getInitiateCheckout();
$search = $block->getSearch();
$orderData = $block->getOrder();

?>
<div id="email"></div>
<script type="text/x-magento-init">
    {
    "*":
    {
            "Dss_FacebookPixel/js/code": {
                "id" : <?= $escaper->escapeHtml($id); ?>,
                "action" : "<?= /* @noEscape */ $data['full_action_name']; ?>",
                "productData" : <?= /* @noEscape */ $product; ?>,
                "categoryData" : <?= /* @noEscape */ $category; ?>,
                "registration" : <?= /* @noEscape */ $registrationData; ?>,
                "addToWishList" : <?= /* @noEscape */ $addToWishlist; ?>,
                "initiateCheckout" : <?=  /* @noEscape */ $initiateCheckout; ?>,
                "search" : <?= /* @noEscape */ $search; ?>,
                "orderData" : <?= /* @noEscape */ $orderData ?>,
                "pageView" : "<?= /* @noEscape */ $pageView; ?>"
            }
        }
    }
</script>
<!-- Facebook Pixel Code -->
<noscript><img height="1" width="1" style="display:none" alt="Facebook Pixel"
               src="https://www.facebook.com/tr?id=<?=  $escaper->escapeHtml($id) ?>&ev=PageView&noscript=1"
    /></noscript>
<!-- End Facebook Pixel Code -->
